"""Every user-visible UI string (Russian). UPPER_CASE str constants only."""

TITLE = "OMNIVOICE"
PAGE_TITLE = "omnivoice"

# Environment badge
ENV_CHECKING = "проверяю окружение…"
NO_GPU = "нет GPU"
GPU_PREFIX = "GPU: "
DOCKER_OK = "Docker ✓"
DOCKER_NO = "Docker ✗"
WSL_OK = "WSL ✓"
WSL_NO_GPU = "WSL: нет GPU"
GPU_DOCKER_NO = " (Docker её не видит)"

# Sidebar
PROJECT = "Проект"
NO_PROJECTS = "Проектов пока нет — создай новый"
NEW_PROJECT = "+ новый проект"
NEW_NAME = "Имя голоса"
NEW_LANGUAGE = "Язык"
CREATE = "Создать"
CREATED = "Проект «{name}» создан"
NAME_REQUIRED = "Укажи имя голоса"
PROJECT_EXISTS = "Папка «{name}» уже существует"
NO_PROJECT_SELECTED = "Сначала выбери или создай проект"

# Sections (also the step chips)
SEC_SETUP = "Установка"
SEC_AUDIO = "Аудио"
SEC_SLICE = "Нарезка"
SEC_PHRASES = "Фразы"
SEC_CHECK = "Проверка"
SEC_TRAIN = "Обучение"
SEC_PACK = "Упаковка"

# Audio
UPLOAD = "Загрузить аудио (можно несколько файлов)"
UPLOADED = "Загружено файлов: {n}"
RAW_FILES = "Файлы в raw/"
RAW_NAME = "файл"
RAW_SIZE = "размер"
ISOLATE = "Отделить голос от музыки"
SLICE = "Нарезать"
SLICING = "Нарезаю {name}"
SLICED_TEXT = "Нарезано фраз: {n}, текст распознан — проверь во «Фразах»"
SLICED_NO_TEXT = ("Нарезано фраз: {n} по паузам, текст не распознан (нет faster-whisper) — "
                  "нажми «Расшифровать» во «Фразах»")
SLICED_NONE = "Новых фраз нет: всё из raw/ уже нарезано или речь не найдена"

# Phrases
ONLY_FLAGGED = "только ⚑"
COL_ID = "id"
COL_TEXT = "текст"
COL_DURATION = "длит., с"
COL_FLAGS = "флаги"
COL_DROPPED = "выкинута"
PLAYER = "Выбранная фраза"
TRANSCRIBE = "Расшифровать"
TRANSCRIBING = "Распознаю {name}"
TRANSCRIBED = "Распознано фраз: {n}"
SAVE_EDITS = "Сохранить правки"
SAVED_EDITS = "Сохранено правок: {n}"
TOGGLE_DROP = "Выкинуть/Вернуть"
DROPPED = "Фраза {id} выкинута"
RESTORED = "Фраза {id} возвращена"
SELECT_ROW = "Сначала выбери фразу в таблице"
PHRASES_DONE = "Готово"
PHRASES_MARKED = "Фразы отмечены как готовые"
STAT_PHRASES = "фраз"
STAT_SPEECH = "речь"
STAT_MINUTES = "мин"
STAT_CHECK = "к проверке"
STAT_DROPPED = "выкинуто"

# Check
CHECK = "Проверить"
CHECK_SUMMARY = "Минут речи: {minutes}, фраз: {phrases}"
CHECK_OK = "Ошибок нет — можно обучать"
CHECK_ISSUES = "Проблемы по фразам"
CHECK_EMPTY = "Нажми «Проверить», чтобы оценить датасет"

# Train
EPOCHS = "Сколько эпох дообучать"
BATCH = "Размер батча"
TRAIN_START = "Старт"
TRAIN_STOP = "Стоп"
TRAIN_RESUME = "Продолжить"
TRAIN_LOG = "Журнал обучения"
TRAIN_LOG_FILE = "Полный журнал (со всеми предупреждениями и прогресс-барами): {path}"
TRAIN_IDLE = "Обучение не запущено"
TRAIN_IDLE_DONE = "Обучение не запущено · уже обучено эпох: {n}"
TRAIN_RUNNING = "ОБУЧЕНИЕ · эпоха {epoch}/{target}"
TRAIN_TIMING = " · {per} на эпоху · осталось ≈ {eta}"
TRAIN_RUNNING_NO_EPOCH = "ОБУЧЕНИЕ · запуск…"
TRAIN_STARTED = "Старт обучения: {epochs} эпох, батч {batch}"
TRAIN_BATCH_AUTO = "по видеопамяти"
TRAIN_DONE = "Обучение завершено"
TRAIN_STOPPED = "Обучение остановлено — нажми «Продолжить»"
TRAIN_FAILED = "Обучение прервалось (код {code}) — см. журнал"
TRAIN_ERROR = "Ошибка обучения — см. журнал"
TRAIN_BUSY = "Обучение уже идёт"
TRAIN_STOPPING = "Останавливаю обучение…"
TRAIN_DOWNLOAD = "Скачиваю базовую модель: {pct}%"
CKPT_SAVED = "Сохранён чекпойнт: {what}"
CHART_MOS = "Качество звучания (MOS, выше — лучше)"
CHART_MEL = "Ошибка (mel, ниже — лучше)"
CHART_EPOCH = "эпоха"
CHART_EMPTY = "Графики появятся после первой эпохи обучения"
CHECKPOINTS = "Чекпойнты (сохранённые состояния модели)"
CKPT_HINT = ("★ — лучший по оценке качества (MOS): обычно его и экспортируют. Но послушай ниже — на первых "
             "эпохах MOS высокий, а голос ещё похож на базовый.")
CKPT_EPOCH = "эпоха {epoch}"
CKPT_MOS = "MOS {v:.2f}"
CKPT_MEL = "mel {v:.3f}"
CKPT_BEST_MOS = "★ лучший по качеству"
CKPT_BEST_MEL = "лучший по mel"
CKPT_LAST = "последний"
CKPT_OLD_LAST = "последний прошлого запуска"
REFRESH = "Обновить"
LISTEN = "Послушать"
LISTEN_HINT = "Так звучит модель на этой эпохе — сравни разные эпохи и экспортируй лучшую."
LISTEN_EPOCH = "Эпоха {epoch}"
LISTEN_NEAREST = "Эпоха {epoch} (ближайшая с записанными фразами)"
LISTEN_NONE = "Для этого чекпойнта нет записанных фраз — они пишутся после каждой эпохи обучения"
PREVIEW = "Фраза {n}"
NO_CHECKPOINTS = "Чекпойнтов пока нет — они появятся после первой эпохи обучения"
EXPORT = "Экспортировать этот чекпойнт"
EXPORTED = "Модель экспортирована: {path}. Дальше — «Упаковка»."
CHOOSE_CHECKPOINT = "Выбери чекпойнт"
DISK = "Место на диске"
DISK_LINE = "Папка train: {size} · чекпойнтов: {n} (каждый ≈ 800 МБ)"
DISK_EXTRA = "Лишних: {n} — можно освободить {size}"
DISK_NOTHING_EXTRA = "Лишних чекпойнтов нет"
PRUNE = "Удалить лишние чекпойнты"
PRUNE_CONFIRM = "Да, удалить"
PRUNE_INFO = "Останутся: лучший по MOS, лучший по mel и последний (для «Продолжить»)"
PRUNE_NEED_CONFIRM = "Поставь галочку «Да, удалить» — удалённые чекпойнты не вернуть"
PRUNE_BUSY = "Идёт обучение — удалять чекпойнты можно после остановки"
PRUNE_RECENT = ("Чекпойнты менялись меньше 3 минут назад — похоже, обучение ещё идёт (в другом окне или в консоли). "
                "Останови его или подожди")
PRUNED = "Удалено чекпойнтов: {n}, освобождено {size}"
COLAB_HINT = ("**Нет видеокарты NVIDIA для Docker** — обучай в Google Colab: скачай датасет кнопкой ниже "
              "и открой [ноутбук omnivoice]({url}).")
COLAB_ZIP = "Скачать датасет для Colab"
COLAB_FILE = "Датасет для Colab"

# Setup (dependencies)
SETUP_INTRO = ("Всё, что нужно для подготовки и обучения: пакеты, ffmpeg и среда обучения WSL "
               "(~15 ГБ в папке для зависимостей, ставится один раз). Уже установленное пропускается.")
SETUP_CHECKING = "Проверяю, что уже установлено…"
SETUP_OPTIONAL = "необязательно"
SETUP_INSTALL = "Установить зависимости"
SETUP_LOG = "Журнал установки"
SETUP_IDLE = "Установка не запущена"
SETUP_RUNNING = "Идёт установка — можно свернуть окно, но не закрывай его"
SETUP_DONE = "Готово — всё установлено"
SETUP_DONE_MISSING = "Установка завершилась, но не всё готово — см. список"
SETUP_REBOOT_TITLE = "Нужна перезагрузка"
SETUP_ERROR = "Установка прервалась"
SETUP_CHECK_FAILED = "Не удалось проверить зависимости: {error}"
SETUP_BUSY = "Установка уже идёт — подожди"
SETUP_STEP = "Шаг {n}/{total}"
SETUP_DOWNLOADING = "Скачиваю: {pct}%"
SETUP_FIRST = "Сначала установи зависимости"
SETUP_FIRST_HINT = "Среда обучения не найдена: ни WSL omnivoice, ни Docker с GPU. Сначала установи зависимости → «Установка»."
SETUP_GOTO = "Перейти к установке"

# Dependency folder (WSL disk, base models, ffmpeg)
DATA_DIR = "Папка для зависимостей"
DATA_DIR_INFO = "Среда WSL, базовые модели и ffmpeg (~15 ГБ). Уже установленное переносится целиком, проекты остаются на месте"
DATA_DIR_MOVE = "Сменить / перенести"
DATA_DIR_FREE = "Свободно на диске {drive} — {free}"
DATA_DIR_NO_DRIVE = "Диск {drive} недоступен"
DATA_DIR_ENV = "Задана переменной окружения OMNIVOICE_CACHE — сменить её можно только там"
DATA_DIR_DONE = "Готово — папка для зависимостей сменена"
DATA_DIR_ERROR = "Перенос не удался"

# Pack
F_NAME = "Имя"
F_DESCRIPTION = "Описание"
F_GENDER = "Пол"
F_SAMPLE = "Фраза-пример"
F_LICENSE = "Лицензия"
PORTRAIT = "Портрет (любая картинка — ужмётся до 32×32)"
PORTRAIT_PREVIEW = "Так он будет выглядеть"
PORTRAIT_BAD = "Не удалось прочитать картинку"
PACK = "Упаковать"
PACKED = "Голос собран: {path}"
SAMPLE_AUDIO = "Пример звучания"
INSTALL_TARGET = "Куда установить (папка models мода)"
INSTALL_OVERWRITE = "Заменить, если уже есть"
INSTALL = "Установить в Minecraft"
INSTALLED = "Голос установлен: {path}"
INSTALL_NO_TARGET = "Укажи папку models мода"
INSTALL_NO_VOICE = "Сначала упакуй голос"

# Errors
ERR_UNKNOWN = "Непредвиденная ошибка — подробности в консоли"
ERR_TITLE = "Ошибка"

# Helpers
BAD_FILE_NAME = "Недопустимое имя файла: {name}"
KB = "КБ"
NO_SEGMENT = "Нет фразы {id}"

# Concurrent operations on one project
PROJECT_BUSY = "Проект занят: идёт {op} — подожди"
OP_SLICE = "нарезка"
OP_TRANSCRIBE = "распознавание"
OP_SAVE = "сохранение правок"
OP_DROP = "изменение фразы"
OP_DONE = "отметка фраз"
OP_CHECK = "проверка"
OP_PACK = "упаковка"
OP_COLAB = "сборка датасета для Colab"
OP_TRAIN = "подготовка обучения"
OP_UPLOAD = "загрузка аудио"
OP_EXPORT = "экспорт в ONNX"
OP_PRUNE = "удаление чекпойнтов"

# Progress / status for slower actions
EXPORTING = "Экспортирую чекпойнт в ONNX…"
REFRESHING = "Ищу чекпойнты…"
LISTENING = "Достаю фразы этой эпохи из журнала обучения…"
ZIPPING = "Собираю датасет для Colab…"
PACKING = "Упаковываю голос…"
VERIFYING = "Проверяю голос в sherpa-onnx…"
COLAB_READY = "Датасет готов: {path}"

# Install target
TARGET_NOT_ABSOLUTE = "Укажи полный путь к папке models (например C:\\…\\models)"
TARGET_NOT_FOUND = "Папка не найдена: {path}"

# Human labels for flag / issue codes (unknown codes are shown as is)
CODE_CHECK = "проверить"
CODE_FOREIGN_LETTERS = "чужие буквы"
CODE_TOO_SHORT = "слишком короткая"
CODE_TOO_LONG = "слишком длинная"
CODE_CLIPPING = "перегруз"
CODE_EMPTY_TEXT = "нет текста"
CODE_UNSPEAKABLE = "непроизносимо"
CODE_MISSING_AUDIO = "нет аудио"

# Not a str constant (lower-case on purpose, so the "UPPER_CASE values are str" rule still holds).
code_labels = {
    "check": CODE_CHECK, "foreign_letters": CODE_FOREIGN_LETTERS, "too_short": CODE_TOO_SHORT,
    "too_long": CODE_TOO_LONG, "clipping": CODE_CLIPPING, "empty_text": CODE_EMPTY_TEXT,
    "unspeakable": CODE_UNSPEAKABLE, "missing_audio": CODE_MISSING_AUDIO,
}
