"""Every user-visible UI string (Russian). UPPER_CASE str constants only."""

TITLE = "OMNIVOICE"
PAGE_TITLE = "omnivoice"

# Environment badge
ENV_CHECKING = "проверяю окружение…"
NO_GPU = "нет GPU"
GPU_PREFIX = "GPU: "
DOCKER_OK = "Docker ✓"
DOCKER_NO = "Docker ✗"
WSL_OK = "WSL ✓"
WSL_NO_GPU = "WSL: нет GPU"
GPU_DOCKER_NO = " (Docker её не видит)"

# Sidebar
PROJECT = "Проект"
NEW_NAME = "Имя голоса"
NEW_LANGUAGE = "Язык"
NEW_BASE = "Базовая модель"
NEW_OPEN = "+ новый проект"
BASE_SAMPLE = "Как звучит {base}"
BASE_SAMPLE_FAILED = "Не удалось скачать пример голоса {base} — проверь интернет"
NEW_INTRO = "Проект — это один голос: его записи, фразы, обучение и готовая модель. Создай его и загрузи аудио."
NEW_NAME_PLACEHOLDER = "например, Артас"
LANG_RU = "Русский"
LANG_EN = "English"
DELETE_PROJECT = "− удалить проект"
DELETE_INTRO = ("Удаляется вся папка проекта со всеми файлами — вернуть её будет нельзя. Голос, уже установленный "
                "в игру, останется. Если нужно только место на диске — удали лишние чекпойнты во вкладке «Чекпойнты».")
DELETE_PARTS = "Что будет удалено"
DELETE_PART_RAW = "Записи (аудио)"
DELETE_PART_SEGMENTS = "Нарезанные фразы"
DELETE_PART_TRAIN = "Обучение и чекпойнты"
DELETE_PART_EXPORT = "Готовые модели (экспорт)"
DELETE_PART_TOTAL = "Всего"
DELETE_CONFIRM = "Для подтверждения введи имя проекта: {name}"
DELETE_BTN = "Удалить проект навсегда"
DELETE_NEED_CONFIRM = "Введи имя проекта «{name}» в поле подтверждения — удалённый проект не вернуть"
DELETE_BUSY = "Идёт обучение этого проекта — останови его перед удалением"
DELETE_RECENT = ("Файлы проекта менялись меньше 3 минут назад — похоже, обучение ещё идёт (в другом окне или в "
                 "консоли). Останови его или подожди")
DELETED = "Проект «{name}» удалён, освобождено {size}"
NEW_BASE_INFO = "От этого голоса дообучается модель — бери того же пола и похожего тембра"
BASE_MALE = "мужской"
BASE_FEMALE = "женский"
TRAIN_BASE = "Базовая модель: {base}"
CREATE = "Создать"
CREATED = "Проект «{name}» создан"
NAME_REQUIRED = "Укажи имя голоса"
PROJECT_EXISTS = "Папка «{name}» уже существует"
NO_PROJECT_SELECTED = "Сначала выбери или создай проект"

# Sections (also the step chips)
SEC_SETUP = "Установка"
SEC_AUDIO = "Аудио"
SEC_SLICE = "Нарезка"
SEC_PHRASES = "Фразы"
SEC_CHECK = "Проверка"
SEC_TRAIN = "Обучение"
SEC_CKPT = "Чекпойнты"
SEC_NEW = "Новый проект"
SEC_DELETE = "Удаление проекта"
SEC_PACK = "Упаковка"

# Audio
UPLOAD = "Загрузить аудио (можно несколько файлов)"
UPLOADED = "Загружено файлов: {n}"
RAW_FILES = "Загруженные записи"
RAW_EMPTY = "Записей пока нет — перетащи аудиофайлы в поле выше"
RAW_TOTAL = "Файлов: {n} · {size}"
RAW_DELETE = "✕"
RAW_DELETE_HINT = "Удалить запись"
PLAY = "Слушать"
RAW_DELETED = ("Запись {name} удалена. Фразы, уже нарезанные из неё, остались — лишние можно выкинуть во «Фразах» "
               "или нарезать заново")
RAW_GONE = "Записи {name} уже нет"
ISOLATE = "Отделить голос от музыки"
SLICE = "Нарезать"
SLICING = "Нарезаю {name}"
SLICED_TEXT = "Нарезано фраз: {n}, текст распознан — проверь во «Фразах»"
SLICED_NO_TEXT = ("Нарезано фраз: {n} по паузам, текст не распознан (нет faster-whisper) — "
                  "нажми «Расшифровать» во «Фразах»")
SLICED_NONE = "Новых фраз нет: всё из raw/ уже нарезано или речь не найдена"

# Phrases
ONLY_FLAGGED = "только ⚑"
COL_ID = "id"
COL_TEXT = "текст"
COL_DURATION = "длит., с"
COL_FLAGS = "флаги"
COL_DROPPED = "выкинута"
PLAYER = "Выбранная фраза"
PHRASES_EMPTY = "Фраз пока нет — загрузи аудио и нажми «Нарезать» во вкладке «Аудио»"
PHRASES_FILTER_EMPTY = "Фраз, которые нужно проверить, нет"
PHRASE_PLACEHOLDER = "Что говорит персонаж…"
PHRASE_SECONDS = "{v:.1f} с"
PHRASE_DROPPED_CHIP = "выкинута"
PHRASE_DROP_HINT = "Выкинуть фразу из обучения"
PHRASE_RESTORE_HINT = "Вернуть фразу"
TEXT_SAVED = "Текст фразы {id} сохранён"
TRANSCRIBE = "Расшифровать"
TRANSCRIBING = "Распознаю {name}"
TRANSCRIBED = "Распознано фраз: {n}"
SAVE_EDITS = "Сохранить правки"
SAVED_EDITS = "Сохранено правок: {n}"
TOGGLE_DROP = "Выкинуть/Вернуть"
DROPPED = "Фраза {id} выкинута"
RESTORED = "Фраза {id} возвращена"
SELECT_ROW = "Сначала выбери фразу в таблице"
PHRASES_DONE = "Готово"
PHRASES_MARKED = "Фразы отмечены как готовые"
STAT_PHRASES = "фраз"
STAT_SPEECH = "речь"
STAT_MINUTES = "мин"
STAT_CHECK = "к проверке"
STAT_DROPPED = "выкинуто"

# Check
CHECK = "Проверить"
CHECK_SUMMARY = "Минут речи: {minutes}, фраз: {phrases}"
CHECK_OK = "Ошибок нет — можно обучать"
CHECK_ISSUES = "Проблемы по фразам"
CHECK_EMPTY = "Нажми «Проверить», чтобы оценить датасет"

# Synth
SEC_SYNTH = "Синтетика"
SYNTH_IDLE = "Синтетика не запущена"
SYNTH_RUNNING = "Генерирую {done}/{total}"
SYNTH_ETA = " · осталось ≈ {eta}"
SYNTH_CHECKING = "Проверяю сгенерированное (Whisper)…"
SYNTH_STOPPING = "Останавливаю: дописываю текущую фразу…"
SYNTH_STOPPED = "Генерация остановлена — «Догенерировать» доделает остальное"
SYNTH_DONE = "Готово: принято {accepted} ({minutes} мин) · спорно {suspect} · брак {rejected} · не удалось {failed}"
SYNTH_FAILED = "Генерация прервалась (код {code}) — см. журнал"
SYNTH_ERROR = "Ошибка генерации — см. журнал"
SYNTH_BUSY = "Генерация уже идёт"
SYNTH_NO_WHISPER = ("Whisper не установлен — фразы не проверены и в обучение не пойдут. Поставь пакеты подготовки "
                    "на «Установке»")
SYNTH_INTRO = ("XTTS v2 озвучит голосом персонажа много новых фраз — Piper учится на них лучше, чем на одной минуте "
               "записей. Голоса с синтетикой XTTS — только для некоммерческого использования.")
SYNTH_NEED_HEAD = "Нужна установка XTTS v2"
SYNTH_NEED_XTTS = "≈ 3–4 ГБ: на «Установке» поставь галочку «и XTTS v2» и нажми «Установить зависимости»"
SYNTH_GOTO_SETUP = "К установке →"
SYNTH_REFS = "Образцы голоса"
SYNTH_REFS_HINT = "3–5 оригинальных фраз, по которым XTTS копирует голос. Лишнюю убери ✕"
SYNTH_REFS_NONE = "Подходящих образцов нет: нужны фразы 3–12 с без меток"
SYNTH_REFS_AUTO = "Подобрать автоматически"
SYNTH_REF_REMOVE = "Убрать из образцов"
SYNTH_SETTINGS = "Что озвучить"
SYNTH_MINUTES = "Сколько минут синтетики"
SYNTH_LINES = "Свои фразы в стиле персонажа (по одной на строку) — озвучиваются первыми"
SYNTH_START = "Сгенерировать"
SYNTH_MORE = "Догенерировать"
SYNTH_STOP = "Стоп"
SYNTH_PHRASES = "Сгенерированные фразы"
SYNTH_F_SUSPECT = "Спорные"
SYNTH_F_ACCEPTED = "Принятые"
SYNTH_F_REJECTED = "Брак"
SYNTH_LIST_EMPTY = "Здесь пусто"
SYNTH_HEARD = "Whisper услышал: «{text}»"
SYNTH_HEARD_NOTHING = "Whisper ничего не услышал"
SYNTH_ACCEPT = "Принять"
SYNTH_DROP = "Выкинуть"
SYNTH_USE = "Использовать синтетику при обучении"
SYNTH_WEIGHT = "Вес оригинала (×)"
SYNTH_LOG = "Журнал генерации"
SYNTH_TRAIN_LINE = "Синтетика: {n} фраз · {minutes} мин"
SETUP_WITH_XTTS = "и XTTS v2 для синтетики (≈ 3–4 ГБ, необязательно)"
STEP_OPTIONAL = "необяз."
SYNTH_NO_REFS = "Нет подходящих фраз-образцов (3–12 с, без меток) — сначала нарежь и проверь оригинал"

# Train
EPOCHS = "Сколько эпох дообучать"
BATCH = "Размер батча"
TRAIN_START = "Старт"
TRAIN_STOP = "Стоп"
TRAIN_RESUME = "Продолжить"
TRAIN_LOG = "Журнал обучения"
TRAIN_LOG_FILE = "Полный журнал (со всеми предупреждениями и прогресс-барами): {path}"
TRAIN_IDLE = "Обучение не запущено"
TRAIN_IDLE_DONE = "Обучение не запущено · уже обучено эпох: {n}"
TRAIN_RUNNING = "ОБУЧЕНИЕ · эпоха {epoch}/{target}"
TRAIN_TIMING = " · {per} на эпоху · осталось ≈ {eta}"
TRAIN_RUNNING_NO_EPOCH = "ОБУЧЕНИЕ · запуск…"
TRAIN_STARTED = "Старт обучения: {epochs} эпох, батч {batch}"
TRAIN_BATCH_AUTO = "по видеопамяти"
TRAIN_DONE = "Обучение завершено"
TRAIN_STOPPED = "Обучение остановлено — нажми «Продолжить»"
TRAIN_FAILED = "Обучение прервалось (код {code}) — см. журнал"
TRAIN_ERROR = "Ошибка обучения — см. журнал"
TRAIN_BUSY = "Обучение уже идёт"
TRAIN_STOPPING = "Останавливаю обучение: дообучаю текущий шаг и сохраняю прогресс…"
TRAIN_STOP_WAIT = "Останавливаю…"
TRAIN_STOP_FORCED = "Обучение не остановилось само — завершаю его принудительно"
TRAIN_DOWNLOAD = "Скачиваю базовую модель: {pct}%"
CKPT_SAVED = "Сохранён чекпойнт: {what}"
CHART_MOS = "Качество звучания (MOS, выше — лучше)"
CHART_MEL = "Ошибка (mel, ниже — лучше)"
CHART_EPOCH = "эпоха"
CHART_EMPTY = "Графики появятся после первой эпохи обучения"
CHECKPOINTS = "Чекпойнты (сохранённые состояния модели)"
CKPT_HINT = ("Нажми на карточку — ниже появятся фразы этой эпохи, её можно экспортировать. ★ — лучший по качеству "
             "(MOS), его обычно и экспортируют. Первые эпохи (разгон) скрыты: MOS там высокий, но голос ещё базовый.")
CKPT_SORT = "Сортировка"
CKPT_SORT_MOS = "по качеству (MOS)"
CKPT_SORT_MEL = "по mel"
CKPT_SORT_EPOCH = "по эпохе"
CKPT_COL_EPOCH = "Эпоха"
CKPT_COL_MOS = "MOS ↑"
CKPT_COL_MEL = "mel ↓"
CKPT_COL_MARKS = "Отметка"
CKPT_SELECTED = "▶ выбран"
CKPT_CHOSEN = "Выбран: {text}"
CKPT_GOTO = "Чекпойнты, прослушивание и экспорт →"
CKPT_EPOCH = "эпоха {epoch}"
CKPT_MOS = "MOS {v:.2f}"
CKPT_MEL = "mel {v:.3f}"
CKPT_BEST_MOS = "★ лучший по качеству"
CKPT_BEST_MEL = "лучший по mel"
CKPT_LAST = "последний"
CKPT_OLD_LAST = "последний прошлого запуска"
CKPT_EXPORTED = "экспортирован"
PACK_MODEL_HEAD = "Модель для упаковки"
PACK_MODEL = "{what} · экспортирована {when}"
PACK_MODEL_UNKNOWN = "Экспортирована {when}, из какой эпохи — неизвестно: экспорт сделан до того, как это стало записываться"
PACK_MODEL_NONE = "Модель ещё не экспортирована — выбери чекпойнт на вкладке «Чекпойнты» и нажми «Экспортировать»"
PACK_MODEL_OTHER = "Другая модель — выбери её на вкладке «Чекпойнты» и экспортируй"
PACK_GOTO_CKPT = "К чекпойнтам →"
REFRESH = "Обновить"
LISTEN = "Послушать"
LISTEN_HINT = "Так звучит модель на этой эпохе — сравни разные эпохи и экспортируй лучшую."
LISTEN_EPOCH = "Эпоха {epoch}"
LISTEN_NEAREST = "Эпоха {epoch} (ближайшая с записанными фразами)"
LISTEN_NONE = "Для этого чекпойнта нет записанных фраз — они пишутся после каждой эпохи обучения"
NO_CHECKPOINTS = "Чекпойнтов пока нет — они появятся после первой эпохи обучения"
EXPORT = "Экспортировать этот чекпойнт"
EXPORTED = "Модель экспортирована: {path}. Дальше — «Упаковка»."
CHOOSE_CHECKPOINT = "Выбери чекпойнт"
DISK = "Место на диске"
DISK_LINE = "Папка train: {size} · чекпойнтов: {n} (каждый ≈ 800 МБ)"
DISK_EXTRA = "Лишних: {n} — можно освободить {size}"
DISK_NOTHING_EXTRA = "Лишних чекпойнтов нет"
PRUNE = "Удалить лишние чекпойнты"
PRUNE_CONFIRM = "Да, удалить"
PRUNE_INFO = "Останутся: лучший по MOS, лучший по mel и последний (для «Продолжить»)"
PRUNE_NEED_CONFIRM = "Поставь галочку «Да, удалить» — удалённые чекпойнты не вернуть"
PRUNE_BUSY = "Идёт обучение — удалять чекпойнты можно после остановки"
PRUNE_RECENT = ("Чекпойнты менялись меньше 3 минут назад — похоже, обучение ещё идёт (в другом окне или в консоли). "
                "Останови его или подожди")
PRUNED = "Удалено чекпойнтов: {n}, освобождено {size}"
COLAB_HINT = ("**Нет видеокарты NVIDIA для Docker** — обучай в Google Colab: скачай датасет кнопкой ниже "
              "и открой [ноутбук omnivoice]({url}).")
COLAB_ZIP = "Скачать датасет для Colab"
COLAB_FILE = "Датасет для Colab"

# Setup (dependencies)
SETUP_INTRO = ("Всё, что нужно для подготовки и обучения: пакеты, ffmpeg и среда обучения WSL "
               "(~15 ГБ в папке для зависимостей, ставится один раз). Уже установленное пропускается.")
SETUP_CHECKING = "Проверяю, что уже установлено…"
SETUP_OPTIONAL = "необязательно"
SETUP_INSTALL = "Установить зависимости"
SETUP_LOG = "Журнал установки"
SETUP_IDLE = "Установка не запущена"
SETUP_RUNNING = "Идёт установка — можно свернуть окно, но не закрывай его"
SETUP_DONE = "Готово — всё установлено"
SETUP_DONE_MISSING = "Установка завершилась, но не всё готово — см. список"
SETUP_REBOOT_TITLE = "Нужна перезагрузка"
SETUP_ERROR = "Установка прервалась"
SETUP_CHECK_FAILED = "Не удалось проверить зависимости: {error}"
SETUP_BUSY = "Установка уже идёт — подожди"
SETUP_STEP = "Шаг {n}/{total}"
SETUP_DOWNLOADING = "Скачиваю: {pct}%"
SETUP_FIRST = "Сначала установи зависимости"
SETUP_FIRST_HINT = "Среда обучения не найдена: ни WSL omnivoice, ни Docker с GPU. Сначала установи зависимости → «Установка»."
SETUP_GOTO = "Перейти к установке"

# Dependency folder (WSL disk, base models, ffmpeg)
DATA_DIR = "Папка для зависимостей"
DATA_DIR_INFO = "Среда WSL, базовые модели и ffmpeg (~15 ГБ). Уже установленное переносится целиком, проекты остаются на месте"
DATA_DIR_MOVE = "Сменить / перенести"
DATA_DIR_FREE = "Свободно на диске {drive} — {free}"
DATA_DIR_NO_DRIVE = "Диск {drive} недоступен"
DATA_DIR_ENV = "Задана переменной окружения OMNIVOICE_CACHE — сменить её можно только там"
DATA_DIR_DONE = "Готово — папка для зависимостей сменена"
DATA_DIR_ERROR = "Перенос не удался"

# Pack
F_NAME = "Имя"
F_DESCRIPTION = "Описание"
F_GENDER = "Пол"
F_SAMPLE = "Фраза-пример"
F_LICENSE = "Лицензия"
PORTRAIT = "Портрет (любая картинка — ужмётся до 32×32)"
PORTRAIT_PREVIEW = "Так он будет выглядеть"
PORTRAIT_BAD = "Не удалось прочитать картинку"
PACK = "Упаковать"
PACKED = "Голос собран: {path}"
SAMPLE_AUDIO = "Пример звучания"
INSTALL_TARGET = "Куда установить (папка models мода)"
INSTALL_OVERWRITE = "Заменить, если уже есть"
INSTALL = "Установить в Minecraft"
INSTALLED = "Голос установлен: {path}"
INSTALL_NO_TARGET = "Укажи папку models мода"
INSTALL_TARGET_INFO = "Найдены сборки с OmniChat. Другую — «Выбрать папку…»: подойдёт папка сборки или папка models"
TARGET_DEV = "Папка разработки (run)"
TARGET_PICK = "Выбрать папку…"
TARGET_PICK_TITLE = "Папка сборки Minecraft или папка models мода OmniChat"
TARGET_PICKED = "Выбрано: {path}"
INSTALL_NO_VOICE = "Сначала упакуй голос"

# Errors
ERR_UNKNOWN = "Непредвиденная ошибка — подробности в консоли"
ERR_TITLE = "Ошибка"

# Helpers
BAD_FILE_NAME = "Недопустимое имя файла: {name}"
KB = "КБ"
NO_SEGMENT = "Нет фразы {id}"

# Concurrent operations on one project
PROJECT_BUSY = "Проект занят: идёт {op} — подожди"
OP_SLICE = "нарезка"
OP_TRANSCRIBE = "распознавание"
OP_SAVE = "сохранение правок"
OP_DROP = "изменение фразы"
OP_DONE = "отметка фраз"
OP_CHECK = "проверка"
OP_PACK = "упаковка"
OP_COLAB = "сборка датасета для Colab"
OP_TRAIN = "подготовка обучения"
OP_UPLOAD = "загрузка аудио"
OP_DELETE_RAW = "удаление записи"
OP_EXPORT = "экспорт в ONNX"
OP_PRUNE = "удаление чекпойнтов"
OP_DELETE = "удаление проекта"

# Progress / status for slower actions
EXPORTING = "Экспортирую чекпойнт в ONNX…"
REFRESHING = "Ищу чекпойнты…"
LISTENING = "Достаю фразы этой эпохи из журнала обучения…"
ZIPPING = "Собираю датасет для Colab…"
PACKING = "Упаковываю голос…"
VERIFYING = "Проверяю голос в sherpa-onnx…"
COLAB_READY = "Датасет готов: {path}"

# Install target
TARGET_NOT_ABSOLUTE = "Укажи полный путь к папке models (например C:\\…\\models)"
TARGET_NOT_FOUND = "Папка не найдена: {path}"

# Human labels for flag / issue codes (unknown codes are shown as is)
CODE_CHECK = "проверить"
CODE_FOREIGN_LETTERS = "чужие буквы"
CODE_TOO_SHORT = "слишком короткая"
CODE_TOO_LONG = "слишком длинная"
CODE_CLIPPING = "перегруз"
CODE_EMPTY_TEXT = "нет текста"
CODE_UNSPEAKABLE = "непроизносимо"
CODE_MISSING_AUDIO = "нет аудио"

# Not a str constant (lower-case on purpose, so the "UPPER_CASE values are str" rule still holds).
code_labels = {
    "check": CODE_CHECK, "foreign_letters": CODE_FOREIGN_LETTERS, "too_short": CODE_TOO_SHORT,
    "too_long": CODE_TOO_LONG, "clipping": CODE_CLIPPING, "empty_text": CODE_EMPTY_TEXT,
    "unspeakable": CODE_UNSPEAKABLE, "missing_audio": CODE_MISSING_AUDIO,
}
